### PR TITLE
Rollback nmstate in case vlan-filtering fails

### LINKED ISSUE #184: Stabilize vlan script
The vlan script is a weak point in the configuration. However, there are few things we may do to make it more stable and predictable.

1. Wait for the bridge to become available before we start configuring.
2. Use nmstate rollback mechanism to revert configuration in case the VLAN script fails.

### PR DESCRIPTION
**Pull request by qinqon**
Closes #184

Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

File: pkg/helper/client.go [hunk 1]
```diff
@@ -80,6 +80,28 @@ func set(state string) (string, error) {
 	return stdout.String(), nil
 }
 
+func Rollback() (string, error) {
+	cmd := exec.Command(nmstateCommand, "rollback")
```
Comment (phoracek) [inline pkg/helper/client.go]: Could you  create a helper function to run nmstatectl commands? This is being duplicated

File: pkg/helper/client.go [hunk 2]
```diff
@@ -56,28 +56,42 @@ func applyVlanFiltering(bridgeName string, ports []string) (string, error) {
...
+				fmt.Printf("failed to write input into stdin: %v\n", err)
+			}
+		}()
 
-	if err = cmd.Run(); err != nil {
-		return "", fmt.Errorf("failed to execute nmstate set: '%v' '%s' '%s'", err, stdout.String(), stderr.String())
 	}
-
+	if err := cmd.Run(); err != nil {
+		return "", fmt.Errorf("failed to execute %s %s: '%v' '%v' '%s'", nmstateCommand, arguments, err, stdout.String(), stderr.String())
```
Comment (phoracek) [inline pkg/helper/client.go]: this was originally '%v' "%s' %s', you changed it to '%v' **'%v'** '%s', which does not match passed stdin/out.

File: pkg/helper/client.go [hunk 3]
```diff
@@ -56,28 +56,42 @@ func applyVlanFiltering(bridgeName string, ports []string) (string, error) {
...
+	}
 	return stdout.String(), nil
+
+}
+
+func set(state string) (string, error) {
+	return nmstatectl([]string{"set", "--no-commit"}, state)
+}
+
+func Rollback() (string, error) {
```
Comment (phoracek) [inline pkg/helper/client.go]: Why is Rollback and Commit public while set and show were private?

File: pkg/helper/client.go [hunk 4]
```diff
@@ -56,28 +56,42 @@ func applyVlanFiltering(bridgeName string, ports []string) (string, error) {
...
+	return nmstatectl([]string{"rollback"}, "")
+}
+
+func Commit() (string, error) {
+	return nmstatectl([]string{"commit"}, "")
```
Comment (phoracek) [inline pkg/helper/client.go]: Don't we need to keep some rollback+commit ID to match the two? nmstatectl is stateless, there has to be a matching mechanism. Or do we just expect there is only a single user of the command?

File: pkg/helper/client.go (hunk 3 above)
Comment (qinqon) [reply pkg/helper/client.go]: We will use it later on for the lose connectivity to API I was expecting to do that outside of client.go, at controller, but we can do that check at ApplyDesiredState

File: pkg/helper/client.go (hunk 4 above)
Comment (qinqon) [reply pkg/helper/client.go]: I think it rollbacks the latest checkpoing, that's why checkpoin is optional in the command.

File: pkg/helper/client.go (hunk 3 above)
Comment (phoracek) [reply pkg/helper/client.go]: I see, still, please keep it private until we will need it elsewhere. Otherwise we may just forget about it

File: pkg/helper/client.go (hunk 4 above)
Comment (phoracek) [reply pkg/helper/client.go]: Gotcha. I think we should create named checkpoint. Makes less space for random issues IMO.

File: pkg/helper/client.go (hunk 3 above)
Comment (qinqon) [reply pkg/helper/client.go]: ack

File: pkg/helper/client.go (hunk 4 above)
Comment (qinqon) [reply pkg/helper/client.go]: Let make this work and pass, then we add checkpoints, what do you think ?

Comment (phoracek) [reply pkg/helper/client.go]: Fair enough

**Comment by SchSeba** [comment]
@qinqon can you please rebase

**Comment by qinqon** [comment]
@SchSeba done, take a look now.

File: test/e2e/rollback_test.go [hunk 5]
```diff
@@ -0,0 +1,54 @@
+package e2e
+
+import (
+	. "github.com/onsi/ginkgo"
+	. "github.com/onsi/gomega"
+
+	nmstatev1alpha1 "github.com/nmstate/kubernetes-nmstate/pkg/apis/nmstate/v1alpha1"
+)
+
+var _ = Describe("NodeNetworkState controller", func() {
```
Comment (phoracek) [inline test/e2e/rollback_test.go]: This description should be about the test module. I think "Rollback" alone is good.

File: test/e2e/rollback_test.go [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+    type: linux-bridge
+    state: up
+    bridge:
+      options:
+        stp:
+          enabled: false
+      port: []
+`)
+	)
+	Context("when there is an error at vlan-filtering", func() {
```
Comment (phoracek) [inline test/e2e/rollback_test.go]: "when an error happens during state configuration"

We don't care what fails, do we?

File: test/e2e/rollback_test.go [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+		BeforeEach(func() {
+			By("Rename vlan-filtering to force failure after nmstatectl set")
```
Comment (phoracek) [inline test/e2e/rollback_test.go]: We do not fail on `nmstatectl set` though. "to force failure during state configuration" may be more precise?

File: test/e2e/rollback_test.go [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+			runAtPods("sudo", "mv", "/usr/local/bin/vlan-filtering", "/usr/local/bin/vlan-filtering.bak")
+		})
+		AfterEach(func() {
+			By("Correct the vlan-filtering script name")
```
Comment (phoracek) [inline test/e2e/rollback_test.go]: This tells me we are fixing something but you never said we are breaking the name. Would you either fix this `By` or the one in `BeforeEach`?

File: test/e2e/rollback_test.go [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+			runAtPods("sudo", "mv", "/usr/local/bin/vlan-filtering.bak", "/usr/local/bin/vlan-filtering")
+			updateDesiredState(br1Absent)
+			for _, node := range nodes {
+				interfacesNameForNodeEventually(node).ShouldNot(ContainElement("br1"))
+			}
+		})
+		It("should rollback nmstate state to previous value", func() {
```
Comment (phoracek) [inline test/e2e/rollback_test.go]: "should rollback failed state configuration"

We should describe that we "fail the configuration" here, since it is not a part of the context description

File: test/e2e/utils.go [hunk 10]
```diff
@@ -216,25 +216,57 @@ func deletePolicy(name string) {
...
 
+func kubectl(arguments ...string) (string, error) {
+	return run("./kubevirtci/cluster-up/kubectl.sh", arguments...)
+}
+
+func nmstatePods() ([]string, error) {
+	output, err := kubectl("get", "pod", "-n", namespace, "--no-headers=true", "-o", "custom-columns=:metadata.name")
+	ExpectWithOffset(1, err).ToNot(HaveOccurred())
+	names := strings.Split(output, "\n")
+	// Command outputs \n at the end of last element so new empty
```
Comment (phoracek) [inline test/e2e/utils.go]: Could you use `TrimSpace` instead?

File: test/e2e/rollback_test.go (hunk 8 above)
Comment (qinqon) [reply test/e2e/rollback_test.go]: Let's reworkd the By

**Comment by qinqon** [comment]
@phoracek what need to get dropped, don't get it.

**Comment by phoracek** [comment]
@qinqon there is a comment in client.go:176:
```
	// TODO: After implementing commit/rollack from nmstate we have to
	//       rollback if vlanfiltering fails
```

**Comment by phoracek** [comment]
ci test please

**Comment by qinqon** [comment]
ci test please

**Comment by qinqon** [comment]
ci test please

File: pkg/helper/client.go [hunk 11]
```diff
@@ -164,22 +173,27 @@ func ApplyDesiredState(nodeNetworkState *nmstatev1alpha1.NodeNetworkState) (stri
 	// we have to enforce it at the desiredState bridges and outbound ports
 	// they will be configured with vlan_filtering 1 and all the vlan id range
 	// set
-	// TODO: After implementing commit/rollack from nmstate we have to
-	//       rollback if vlanfiltering fails
 	bridgesUpWithPorts, err := getBridgesUp(nodeNetworkState.Spec.DesiredState)
 	if err != nil {
```
[the remark this answers is not in the document]
Comment (qinqon) [reply pkg/helper/client.go]: Yep, let's wrap it.

**Comment by qinqon** [comment]
This is how traces look now 

```json
{"level":"info","ts":1570104042.659638,"logger":"controller_nodenetworkstateconfiguration","msg":"Reconciling NodeNetworkStateConfiguration","Request.Namespace":"","Request.Name":"node01"}
{"level":"info","ts":1570104042.7493527,"logger":"controller_nodenetworkstatereport","msg":"Reconciling NodeNetworkState report","Request.Namespace":"","Request.Name":"node01"}
{"level":"info","ts":1570104043.1400118,"logger":"controller_nodenetworkstatereport","msg":"Reconciling NodeNetworkState report","Request.Namespace":"","Request.Name":"node01"}
{"level":"error","ts":1570104043.4481022,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"nodenetworkstateconfiguration-controller","request":"/node01","error":"error reconciling nodenetworkstate at desired state apply: rollback cause: failed to execute vlan-filtering: 'exec: \"vlan-filtering\": executable file not found in $PATH', '', '', rollback error: <nil>","stacktrace":"github.com/nmstate/kubernetes-nmstate/vendor/github.com/go-logr/zapr.(*zapLogger).Error
```
