### PR TITLE
knmstate, docs: Remove docker caching

### LINKED ISSUE #637: [Flake-CI] Job publish-kubernetes-nmstate of type postsubmit ended with state failure
**What happened**:
Build failed after ~6 minutes.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubernetes-nmstate/1328235972407595008
**What you expected to happen**:
To Build and run tests.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

/kind bug
/triage build-watcher

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:
knmstate, docs: Don't cache builder

The current docs builder caching mechanism is implemented as a
container that use the FROM clausule from the same container that's
pretty wrong since you get never ending layers, let's just remove that
cache and think about it if it's necessary, we are talking about mintues.

**Special notes for your reviewer**:
Closes #637 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: automation/publish.sh [hunk 1]
```diff
@@ -8,39 +8,43 @@
...
+    )
     echo -e "\033[0;32mdemo updated $(date +"%d.%m.%Y %H:%M:%S")\033[0m"
-    git checkout $docs_source_branch --quiet
+}
+
+#push_handler
+
+# We don't have a versioned docs webpage so we only update it from master and
+# not from release branches
+if [ "$branch" == $docs_source_branch ]; then
```
Comment (phoracek) [inline automation/publish.sh:48]: But this will be always master, no?

File: automation/publish.sh [hunk 2]
```diff
@@ -8,39 +8,43 @@
...
+        cd /tmp/gh-pages
+        git add -A
+        git commit -m "updated $(date +"%d.%m.%Y %H:%M:%S")"
+        git push https://kubevirt-bot@github.com/nmstate/kubernetes-nmstate gh-pages
+    )
     echo -e "\033[0;32mdemo updated $(date +"%d.%m.%Y %H:%M:%S")\033[0m"
-    git checkout $docs_source_branch --quiet
+}
+
+#push_handler
```
Comment (phoracek) [inline automation/publish.sh:44]: This should not be commented

File: automation/publish.sh [hunk 3]
```diff
@@ -8,39 +8,43 @@
...
+    make -C docs install build
+    rm -rf /tmp/gh-pages
+    git clone http://github.com/nmstate/kubernetes-nmstate -b gh-pages /tmp/gh-pages
+    git -C /tmp/gh-pages rm -r \* --quiet
+    cp -r docs/build/kubernetes-nmstate/* /tmp/gh-pages
+    (
+        cd /tmp/gh-pages
+        git add -A
+        git commit -m "updated $(date +"%d.%m.%Y %H:%M:%S")"
+        git push https://kubevirt-bot@github.com/nmstate/kubernetes-nmstate gh-pages
```
Comment (phoracek) [inline automation/publish.sh:39]: Should not be the username obtained from an environment variable? Feel weird to hardcode it here

File: automation/publish.sh [hunk 4]
```diff
@@ -8,39 +8,43 @@
...
 
+publish_docs() {
     # Update gh-pages branch with the generated documentation
-    git checkout gh-pages --quiet
-    git rm -r --quiet *
-    docker run -v $(pwd):/gh-pages $docs_container bash -c "cp -r docs/build/kubernetes-nmstate/* /gh-pages"
-    git add -A
-    git commit -m "updated $(date +"%d.%m.%Y %H:%M:%S")"
-    git push --quiet
+    make -C docs install build
```
Comment (phoracek) [inline automation/publish.sh:30]: You should use `        cd ${TMP_PROJECT_PATH}`. Otherwise we just happen to be in the directory as a side effect of a previous function.

File: automation/publish.sh [hunk 5]
```diff
@@ -8,39 +8,43 @@
...
+    rm -rf /tmp/gh-pages
+    git clone http://github.com/nmstate/kubernetes-nmstate -b gh-pages /tmp/gh-pages
```
Comment (phoracek) [inline automation/publish.sh:32]: Why do we fetch it? We should have the sourcecode availble in the job, no?

**Review by phoracek — CHANGES_REQUESTED** [review]
Please mention why are we doing this in the commit message

File: automation/publish.sh (hunk 1 above)
Comment (qinqon) [reply automation/publish.sh:48]: I was thinking that we should run publish.sh at release branches since we want to run knmstate from release- branch HEAD but I think we are just running publish.sh at master so you right.

File: automation/publish.sh (hunk 3 above)
Comment (qinqon) [reply automation/publish.sh:39]: I am following what project-infra does for kubevirtci release, they harcoded the user but I can change that.

File: automation/publish.sh (hunk 5 above)
Comment (qinqon) [reply automation/publish.sh]: I don't want to change where prow is pointing to in the clone, that's why I just clone the branch and push it.

File: automation/publish.sh (hunk 3 above)
Comment (qinqon) [reply automation/publish.sh]: Let me add and env var with it in the project-infra PR

File: docs/_config.yaml [hunk 6]
```diff
@@ -4,8 +4,8 @@ locale: "en-US"
 title: "The Kubernetes NMState project"
 description: A declarative API for Kubernetes node network management
 name: "The Kubernetes NMState team"
-url: "https://nmstate.github.io"
-baseurl: "/kubernetes-nmstate"
+url: "https://storage.googleapis.com"
```
Comment (phoracek) [inline docs/_config.yaml:7]: Why do you change this? Would not it break the page?

File: automation/publish.sh [hunk 7]
```diff
@@ -8,39 +8,32 @@
...
-    # Update kubernetes-nmstate documentation container
-    docker build docs --build-arg BRANCH=$docs_source_branch -t $docs_container
-    docker push $docs_container
-
-    # To pass user/password from automations, idea is taken from [1]
-    # [1] https://stackoverflow.com/questions/8536732/can-i-hold-git-credentials-in-environment-variables
-    git config credential.helper '!f() { sleep 1; echo "username=${GITHUB_USER}"; echo "password=${GITHUB_TOKEN}"; }; f'
+}
 
+publish_docs() {
```
Comment (phoracek) [inline automation/publish.sh:23]: This should happen only on the doc branch, no?

**Review by phoracek — CHANGES_REQUESTED** [review]

File: docs/_config.yaml (hunk 6 above)
Comment (qinqon) [reply docs/_config.yaml:7]: This is from manual call to publish.sh, thanks !

File: automation/publish.sh (hunk 7 above)
Comment (qinqon) [reply automation/publish.sh:23]: we publish from `master` into `gh-pages` branch, is the way github pages works.

File: automation/publish.sh (hunk 4 above)
Comment (qinqon) [reply automation/publish.sh]: Done

**Review by phoracek — APPROVED** [review]
/lgtm
/approve
